applications:
- api_domain: fdpg.test.forschen-fuer-gesundheit.de
  application_name: fdpg
  authentication_key: Authorization
  authentication_mode: header-bearer
  authentication_value: ${{ jit_secrets.api_scan_authentication_value }}
  exclude_paths: []
  target_url: https://github.com/rkuhn-drivebyte/feasibility-backend/blob/develop/src/main/resources/static/v3/api-docs/swagger.yaml
  type: api
